import type { Metadata } from "next";
import "./styles/globals.css";
import "./styles/components.css";
import Sidebar from "./lib/components/sideBar";
import { AuthProvider } from "./context/authContext";
import RequireAuth from "./authentication/requireAuth";
import styles from './dashboard.module.css'


export const metadata: Metadata = {
  title: "Supplier Risk Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <RequireAuth>
            <div className={styles.landingRoot}>
              <Sidebar />
              <div className={styles.pageContainerWithSidebar}>
                {children}
              </div>
            </div>
          </RequireAuth>
        </AuthProvider>
      </body>
    </html>
  );
}
